### ISSUE TITLE
action error

### ISSUE THREAD

**Issue by dxball** [JacobLinCool/Bahamut-Automation#37]
version: 1.0.0-pre.3

modules: `report,ad_handler,login,sign,guild,answer,lottery_plus,logout,discord,line_notify`

error message: 
```
> bahamut-automation@1.0.0-pre.3 prepare /Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action
> npm audit fix --silent

up to date in 1.459s

29 packages are looking for funding
  run `npm fund` for details

fixed 0 of 0 vulnerabilities in 249 scanned packages
added 247 packages from 238 contributors and audited 249 packages in 29.823s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Dependencies NPM Installed
Installing Playwright Dependencies...
Playwright Dependencies Installed
Installing Browser Dependencies...
Browser Dependencies Installed
(node:871) UnhandledPromiseRejectionWarning: ReferenceError: core is not defined
    at main (/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/action.js:45:9)
    at Object.<anonymous> (/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/action.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
(node:871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

works in local machine (win10) but not in github action

**Comment by JacobLinCool** [comment]
@dxball 

I believe the failure happened during the transformation between GitHub Action parameters and Bahamut Automation parameters.

The `ReferenceError: core is not defined` located at line 45, which is in a `catch` block without `core` definition. (This is a bug, but not the cause of the failure.)

The real cause is in the `try` block above, which contains parameter transformation and other parts. 

I can run this version on GitHub Action, so the cause should be something in your `automation.yml`.

You can edit your configuration (`automation.yml`) and do some tests about it.

[action.js L24-L43](https://github.com/JacobLinCool/Bahamut-Automation/blob/action/action.js#L24-L43)

**Comment by charleschiu2012** [comment]
I could also run 1.0.0-pre.3 on Github Action flawlessly.

**Comment by dxball** [comment]
OK, I found the error
My json setting has an extra comma -_-

Thanks for help
