### ISSUE TITLE
automation.yml 設定 @action 卻是顯示執行 v0.6.8 而不是最新的 v0.6.9 ?

### ISSUE THREAD

**Issue by SyaoranChang** [JacobLinCool/Bahamut-Automation#9]
你好,

Run JacobLinCool/Bahamut-Automation@action
卻是顯示執行 v0.6.8 而不是最新的 v0.6.9 ?

![Snipaste_2021-08-25_12-12-48](https://user-images.githubusercontent.com/18550228/130725971-119b9185-87f9-4df1-b15f-f2daad8e33d8.png)

**Comment by SyaoranChang** [comment]
我手動改為 Bahamut-Automation@v0.6.9 後
自動化反動跳出找不到檔案的錯誤

`Run JacobLinCool/Bahamut-Automation@v0.6.9
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/v0.6.9/action.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/v0.6.9/action.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/v0.6.9/action.js'
  ]
***`

![Snipaste_2021-08-25_12-23-52](https://user-images.githubusercontent.com/18550228/130726299-6cfe7155-c305-469a-adf8-f3b940f96210.png)

**Comment by JacobLinCool** [comment]
@SyaoranChang 
已確認問題。

顯示 `v0.6.8` 的原因是因為忘了改版本（字串忘記改了，實際執行內容是 `v0.6.9`）。

而 `@action` 無法執行的原因是因為 release 標錯 branch 。

等等我會做修正，修正完成會再通知你，非常感謝你的提醒。

**Comment by JacobLinCool** [comment]
@SyaoranChang 
我已經重新 tag `v0.6.9`，目前應該能正常使用 `@action` 及 `@v0.6.9` 且皆顯示為 `v0.6.9`。
